#! /usr/bin/env -S awk -f

# SPDX-License-Identifier: BlueOak-1.0.0
# SPDX-FileCopyrightText: 2026 Saulius Krasuckas <saulius2_at_ar-fi_point_lt> | sskras

# Convert the NT DIR output to a list of full pathnames of the directory child items.

/\xff/ \
{
    gsub("\xFF", "_")
}

function Process_item(Filename, Timestamp)
{
    print Filename
}

# Start of dirlist found:

/^ Directory of/ \
{
    sub(/^ Directory of /, "")
    Dir = $0
}

# End of dirlist found:

Dir && /[0-9] File\(s\)/ \
{
    Process_item( Curr_dir_line )
    Dir = ""
}

# Process every child item of the directory (except for the parent dir, AKA "..")
# whose date is 2000+ (TODO some matching flexibility):

Dir && /^2/ && !/\.\.$/ \
{
    # Add trailing backslash to the dirname so after removal
    # of the leading string we could still know it's a dir:

    if ($0 ~ "<DIR>")
        sub(/$/, "\\")

    Timestamp = $1"  "$2
    Leading_str = Timestamp "    +(<DIR> +|[0-9_]+ )"

    # Remove the string leading the name of a child item of the dir:
    Item_name = gensub(Leading_str, "", 1)
    Item_path = Dir "\\" Item_name

    # Fix the timestamp so it becomes a single token, eg:
    # `2010-02-12  10:03` => `2010-02-12T10:03`
    sub(/ +/, "T", Timestamp)

    # Assemble the line of an enumerated item:
    Item = sprintf ("%s %s", Timestamp, Item_path)

    # Got the current dir ?
    if ( $NF == ".\\" )
    {
        # Trim the trailing, reduntant `.\` substring:
        sub (/\.\\$/, "", Item)

        # Save the dir for processing later, following all child items:
        Curr_dir_line = Item
        next
    }

    # Print every child item found in the current dir:
    Process_item( Item )
}
